### ISSUE TITLE
script not running - "Error: Error: osascript is not allowed assistive access."

### ISSUE THREAD

**Issue by allyson-c** [alfredapp/banner-be-gone-workflow#2]
### Workflow version

2023.2

### Alfred version

5.1.4 (2195)

### macOS version

14.3 (23D56)

### Debugger output

```alfred_debugger
[07:03:16.388] Banner Be Gone[Keyword] Processing complete
[07:03:16.389] Banner Be Gone[Keyword] Passing output '' to Run Script
[07:03:16.566] ERROR: Banner Be Gone[Run Script] /Users/duran/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/3295EF82-BC33-420B-BE91-E1D409075EF7: execution error: Error: Error: osascript is not allowed assistive access. (-1719)
[07:03:22.362] Logging Stopped.
```

### More details

Ran the keyword "notclear", and expected notification banner to clear, but it did not clear.

I added terminal to the accessibility privileges, but couldn't figure out where this osascript was to add it to the accessibility list.

**Comment by allyson-c** [comment]
Alfred is already part of the accessibility list, for reference

**Comment by vitorgalvao** [comment]
> Alfred is already part of the accessibility list, for reference

[Remove it and regrant permissions](https://www.alfredapp.com/help/getting-started/permissions/#regrant), because that definitely looks like one of those situations where the permissions are broken (unfortunately becoming a thing on macOS).

**Comment by allyson-c** [comment]
Appreciate the help! I'm getting the following new error now:

> [22:35:56.924] Banner Be Gone[Keyword] Processing complete
> [22:35:56.932] Banner Be Gone[Keyword] Passing output '' to Run Script
> [22:35:57.177] ERROR: Banner Be Gone[Run Script] /Users/duran/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F3F6E1DD-C76D-4B71-861D-9DB9FD14024F: execution error: Error: Error: Invalid index. (-1719)

I went ahead and tried to re-download the workflow, but the error remains.

**Comment by vitorgalvao** [comment]
For that one, see https://github.com/alfredapp/banner-be-gone-workflow/issues/1#issuecomment-1757290826.

I’ll also need a video.

**Comment by allyson-c** [comment]
OK, I think I got it to work! My computer was refusing to index spotlight correctly-- although I think I still have some issues indexing the "Library" folder-- so I just wiped my computer and restored it using Time Machine. I think the Data SSD was corrupted for some reason.

That being said, although the index issue still pops up for me, apparently this script works fine now. Thanks for your help.
