### ISSUE TITLE
Shows desktop and opens widget search when activated

### ISSUE THREAD

**Issue by arturasvlt** [alfredapp/banner-be-gone-workflow#6]
### Workflow version

Newest

### Alfred version

5.5

### macOS version

15.0.1

### Debugger output

```alfred_debugger
Well, when I trigger this workflow on alfred - the computer simply shows up the desktop and also opens a widget app to search for a wider. Sounds very weird but that's just it. Never happened before.
```

**Comment by vitorgalvao** [comment]
Please follow the template. I need the *exact* version of the workflow and the debugger contents, otherwise it’s impossible to diagnose. Also, you’re a version behind on Alfred, please install version 5.5.1.
