### ISSUE TITLE
Unable to clear all notifications at once on macos 15.1

### ISSUE THREAD

**Issue by persiliao** [alfredapp/banner-be-gone-workflow#8]
### Workflow version

v2024.4

### Alfred version

5.5

### macOS version

15.1

### Debugger output

```alfred_debugger
none
```

**Comment by vitorgalvao** [comment]
Yeah, that happens. This needs to use some GUI automation solutions that are undocumented and Apple keeps breaking. I know that if you have a ton of notifications at once it may need a second call, but that’s just how it is.

**Comment by persiliao** [comment]
It does. It takes two each time.

**Comment by vitorgalvao** [comment]
@persiliao I just had a simple idea on how to improve this. Early tests seem quite promising. Update to 2024.5.

**Comment by ngocphamm** [comment]
@vitorgalvao I'm not sure I truly understand this workflow. Is it supposed to clear all notification in the Notification Center. I have this spam text coming in, and I use Alfred, type `notclear` and hit Enter, but it doesn't make the notification go away. I'm using `15.1`.

![CleanShot 2024-12-06 at 11 27 30@2x](https://github.com/user-attachments/assets/c67fc729-dc5c-4360-aebb-e92f70f98125)

**Comment by vitorgalvao** [comment]
> Is it supposed to clear all notification in the Notification Center.

No. It clears visible notifications, as per the instructions. The ones that interrupt you. It specifically is not made for notifications tucked away in the Notification Center, those are auto-cleared every week by macOS anyway.

**Comment by ngocphamm** [comment]
That's what I thought but for some reason was unclear to me. Thanks for clarifying!

**Comment by Ender-Wang** [comment]
I am on 14.7.2, and having the same issue with v2024.5, rolled back to v2024.1 and it then works flawlessly.
